# permissions for end users to edit airflowbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: airflowbase-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airflow-on-k8s-operator
    app.kubernetes.io/part-of: airflow-on-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflowbase-editor-role
rules:
- apiGroups:
  - airflow.apache.org.airflow.apache.org
  resources:
  - airflowbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.apache.org.airflow.apache.org
  resources:
  - airflowbases/status
  verbs:
  - get
