# permissions for end users to view airflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: airflowcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airflow-on-k8s-operator
    app.kubernetes.io/part-of: airflow-on-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflowcluster-viewer-role
rules:
- apiGroups:
  - airflow.apache.org.airflow.apache.org
  resources:
  - airflowclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.apache.org.airflow.apache.org
  resources:
  - airflowclusters/status
  verbs:
  - get
